define: DUK_USE_HSTRING_CLEN
feature_enables: DUK_OPT_HSTRING_CLEN
introduced: 1.5.0
default: true
tags:
  - lowmemory
  - experimental
description: >
  When DUK_USE_STRLEN16 enabled, indicates whether the character length
  (clen16) field should be actually present (default) or computed on-the-fly.

  When clen is computed on-the-fly the duk_hstring structure will be 4 bytes
  smaller which may be useful for very low memory targets.
